create table if not exists public.map_styles (
 id bigint generated by default as identity primary key,
 name text not null,
 style_json jsonb not null,
 created_at timestamptz not null default now()
);
alter table public.map_styles enable row level security;
grant select,insert on public.map_styles to anon;
grant usage,select on sequence public.map_styles_id_seq to anon;
drop policy if exists "Public can read map styles" on public.map_styles;
create policy "Public can read map styles" on public.map_styles for select to anon using (true);
drop policy if exists "Public can insert map styles" on public.map_styles;
create policy "Public can insert map styles" on public.map_styles for insert to anon with check (true);